# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17.4.0
        uses: actions/setup-node@v2
        with:
          node-version: 17.4.0
          cache: "npm"
      - run: npm ci
      - run: npm run vite:build
      - run: npm run electron:build
      - name: Deploy to CVM by SSH
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          # Private Key
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOYSSHKEY }}
          # Remote host
          REMOTE_HOST: cooocc.com
          # Remote user
          REMOTE_USER: root
          # Remote port
          REMOTE_PORT: 22 # optional, default is 22
          # Source directory
          SOURCE: /package.zip # optional, default is
          # Target directory
          TARGET: /datadisk/projects/dynamic-wallpaper # optional, default is /home/REMOTE_USER/
          # Arguments to pass to rsync
          ARGS: -rltgoDzvO # optional, default is -rltgoDzvO
          # An array of folder to exclude
          #EXCLUDE: # optional, default is
