# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    push: 
      branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      GH_TOKEN: ${{ secrets.GITHUBACTIONKEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js lts/*
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "npm"
      # - run: npm install
      # - run: npm run vite:build
      # - run: npm run electron:build
      # - name: Release to Github
      #   uses: softprops/action-gh-release@v1
      #   if: ${{ matrix.os == 'windows-latest' }}
      #   with:
      #     files: "package.json"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUBACTIONKEY }}
      - name: Deploy to CVM by SSH
        uses: easingthemes/ssh-deploy@v2.2.11
        with: 
          # Private Key
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOYSSHKEY }}
          # Remote host
          REMOTE_HOST: cooocc.com
          # Remote user
          REMOTE_USER: root
          # Remote port
          REMOTE_PORT: 22 # optional, default is 22
          # Source directory
          SOURCE: package.json # optional, default is 
          # Target directory
          TARGET: /datadisk/wallpaper # optional, default is /home/REMOTE_USER/
          # Arguments to pass to rsync
          ARGS: -rltgoDzvO # optional, default is -rltgoDzvO
          # An array of folder to exclude
          #EXCLUDE: # optional, default is 
        
        
