# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      #- run: git config GH_TOKEN ${{ secrets.PERSONEL_TOKEN }}
      - name: Use Node.js 17.4.0
        uses: actions/setup-node@v2
        with:
          node-version: 17.4.0
          cache: "npm"
      - run: npm ci
      - run: npm run vite:build
      - run: npm run electron:build
        env:
          GH_TOKEN: ${{ secrets.PERSONEL_TOKEN }}
      - name: Notify me by mail
        uses: devellany/send-mailer@v1.0.2
        with:
          host: smtp.qq.com
          port: 25
          account: 1102358133
          password: uizozunypahfidfc
          sender: Github actions
          from: 1102358133@qq.com
          to: mail@isdtj.com
          subject: 动态壁纸构建好啦
          body: Github actions
          contentType: text/plain
      - name: Release to Github
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "package.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONEL_TOKEN }}
