# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    push: 
      branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
    env:
      GH_TOKEN: ${{ secrets.GITHUBACTIONKEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js latest
        uses: actions/setup-node@v2
        with:
          node-version: latest
          cache: "npm"
      - run: npm ci
      - run: npm run vite:build
      - run: npm run electron:build
      - name: Release to Github
        uses: softprops/action-gh-release@v1
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          files: "packages/*.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBACTIONKEY }}
        
